blank_issues_enabled: true
contact_links:
  - name: Ask a question ‚ùì
    url: https://github.com/Rviewer-Challenges/api-skeleton-py-flask/discussions/new
    about: Ask a question or request support for using this skeleton